# These are supported funding model platforms

github: [MMoMM-Marcus]
patreon: # Replace with a single Patreon username
ko_fi: mmomm
custom: ["https://www.buymeacoffee.com/mmomm"]# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
