import esbuild from "esbuild";
import builtins from 'builtin-modules'
import {copy} from "esbuild-plugin-copy";
import { updateVault } from './update-vault.mjs';

const TEST_VAULT = 'Dynbedded';
const PLUGIN_ID = 'obsidian-dynbedded';

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const dev = (process.argv[2] === 'dev' || process.argv[3] === 'dev');
const devbuild = (process.argv[2] === 'devbuild');
const PLUGINS_PATH = '/.obsidian/plugins/';

let outfile;
if (dev || devbuild) {
	outfile = TEST_VAULT + PLUGINS_PATH + PLUGIN_ID +'/main.js';
} else {
	outfile = './build/main.js';
}

const options = {
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2018',
	logLevel: "info",
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: outfile,
	// copy plugin only runs for dev/devbuild — production build artifacts are
	// assembled explicitly by createZip.sh; build/ is not committed to git
	plugins: prod ? [] : [
		copy({
			assets: [
				{ from: './manifest.json', to: './manifest.json' },
				{ from: './styles.css', to: './styles.css' },
			],
		}),
	],
};

if (dev) {
	const ctx = await esbuild.context(options);
	await ctx.watch();
} else {
	if (devbuild) await updateVault();
	await esbuild.build(options).catch(() => process.exit(1));
}
